- alias: 'Nach Sonnenuntergang Deko einschalten'
  trigger:
    platform: sun
    event: sunset
  action:
    service: light.turn_on
    entity_id: light.deko

- alias: 'Vor Sonnenaufgang Deko ausschalten'
  trigger:
    platform: sun
    event: sunrise
  action:
    service: light.turn_off
    entity_id: light.turn_off

