- alias: 'Turn on TV fix'
  trigger:
    platform: event
    event_type: call_service
    event_data:
      domain: media_player
      service: turn_on
      service_data:
        entity_id: media_player.panasonic_viera_tv      
  action:
    - service: media_player.turn_on
      data:
        entity_id: media_player.denon_avrx1000
    - wait_template: "{{ not is_state('media_player.denon_avrx1000', 'off') }}"
      timeout: 00:00:05
    - delay: 00:00:01
    - service: switch.turn_on
      entity_id: switch.broadlink_panasonic_power
    - wait_template: "{{ not is_state('media_player.panasonic_viera_tv', 'off') }}"
      timeout: 00:00:30
