- alias: "Start when turning on Chromecast"
  trigger:
    platform: event
    event_type: call_service
    event_data:
      domain: media_player
      service: turn_on
      service_data:
        entity_id: media_player.chromecast
  action:
    - service: media_player.turn_on
      data:
        entity_id: media_player.denon_avrx1000
    - wait_template: "{{ not is_state('media_player.denon_avrx1000', 'off') }}"
    - service: media_player.select_source
      data:
        entity_id: media_player.denon_avrx1000
        source: Chromecast

- alias: "Start when turning on FireTV"
  trigger:
    platform: event
    event_type: call_service
    event_data:
      domain: media_player
      service: turn_on
      service_data:
        entity_id: media_player.firetv
  action:
    - service: media_player.turn_on
      data:
        entity_id: media_player.denon_avrx1000
    - wait_template: "{{ not is_state('media_player.denon_avrx1000', 'off') }}"
    - service: media_player.select_source
      data:
        entity_id: media_player.denon_avrx1000
        source: FireTV
